In [1]:
import numpy as np
import numpy.linalg as la
from sklearn.cluster import KMeans
from scipy.linalg import fractional_matrix_power as f_mat_pow
from sklearn.preprocessing import normalize as normalise

In [2]:
import time
def herm(A, k, ϵ):
    n, m = A.shape
    assert n == m
    assert (A == A.H).all()
    start = time.time()
    λ, g = la.eigh(A)
    end = time.time()
    print("Calculating eigenpairs took", end-start)
    g = g[:, np.abs(λ) > ϵ]
    start = time.time()
    P = np.real(g @ g.H)
    end = time.time()
    print('calculating P took', end-start)
    start = time.time()
    kmeans = KMeans(n_clusters=k).fit(P)
    end = time.time()
    print("Clustering took", end-start)
    return kmeans.labels_

In [43]:
def hard_cycle(c,m):
    A = np.matrix(np.zeros((m*c,m*c), dtype=complex))
    for i in range(c):
        A[m*i:m*(i+1), m*((i+1)%c):m*((i+1)%c+1)] =  1j
        A[m*((i+1)%c):m*((i+1)%c+1), m*i:m*(i+1)] = -1j
    return A

In [ ]:
A = hard_cycle(100, 100)
#A = np.matrix(np.triu(np.matrix(1j*np.ones((50,50))), 1) - np.tril(1j*np.matrix(np.ones((50,50))),-1))
print('Created A')
herm(A, 5, 0.01).reshape(5,-1)

In [44]:
A = hard_cycle(100, 100)
#A = np.matrix(np.triu(np.matrix(1j*np.ones((50,50))), 1) - np.tril(1j*np.matrix(np.ones((50,50))),-1))
print('Created A')
herm(A, 100, 0.01).reshape(100,-1)

Created A
Calculating eigenpairs took 1203.8101615905762
calculating P took 2.4294815063476562
Clustering took 370.667688369751


array([[ 0,  0,  0, ...,  0,  0,  0],
       [28, 28, 28, ..., 28, 28, 28],
       [ 2,  2,  2, ...,  2,  2,  2],
       ...,
       [ 8,  8,  8, ...,  8,  8,  8],
       [ 5,  5,  5, ...,  5,  5,  5],
       [15, 15, 15, ..., 15, 15, 15]], dtype=int32)

In [ ]:
_

In [ ]:
_34.mean(axis=1)

In [39]:
mat = lambda m : np.matrix(m)

def disim(A, ky, kz, τ=None):
    n, m = A.shape
    assert n==m
    K = min(ky, kz)
    out_degrees = A.sum(axis=1)
    in_degrees = A.sum(axis=0)
    τ = out_degrees.mean() if τ == None else τ
    Pτ = mat(np.diagflat(in_degrees + τ))
    Oτ = mat(np.diagflat(out_degrees + τ))
    tmp1 = f_mat_pow(Oτ, -0.5)
    tmp2 = f_mat_pow(Pτ, -0.5)
    L =  tmp1 @ A @ tmp2
    start = time.time()
    U, Σ, V = la.svd(L)
    end = time.time()
    print('svd took', end-start)
    XL = U[:, np.argsort(Σ)[-K:]]
    XR = V.T[:, np.argsort(Σ)[-K:]]
    XL_, XR_ = normalise(XL), normalise(XR)
    X_ = np.zeros((2*n, K))
    X_[:n, :] = XL_
    X_[n:, :] = XR_
    start = time.time()
    kmeans = KMeans(n_clusters=K).fit(X_)
    end = time.time()
    print('clustering took', end-start)
    return kmeans.labels_

In [40]:
B = np.maximum(np.imag(hard_cycle(100,100)), 0)
disim(B, 100, 100).reshape(2,-1)

svd took 371.7121548652649
clustering took 7.779682397842407


array([[66, 66, 66, ..., 76, 76, 76],
       [76, 76, 76, ..., 27, 27, 27]], dtype=int32)

In [41]:
np.ones((100,100))[:, np.argsort([10,9,1])[-3:]]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1